[package]
name = "template-rust-cli-core"
description = "Rust CLI template with CI, releases and docs."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true
